### ISSUE TITLE
Минимизировать reflow

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/slider-jquery-plugin#10]
https://github.com/lndbaryshnikov/slider-jquery-plugin/blob/621d58ebcff5d0fb84e51c1819c49091fbe044fb/app/src/plugin/View/LabelsView.ts#L76-L77
Здесь ты в цикле добавляешь элементы в DOM-дерево, что влияет на производительность, каждый раз вызывая `reflow`. Об этом также написано в наших стандартах ([п. 2 здесь](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/performance.md))

Для оптимизации работы следует использовать `DocumentFragment`, в этом случае `reflow` будет произведен единожды независимо от количества элементов, находящихся внутри такого фрагмента

**Comment by lndbaryshnikov** [comment]
Вопрос решен в переписке, принято решение пока оставить как есть. С пунктом в стандартах знаком, здесь же каждая метка рендерится последовательно в dom из следующих соображений: размер метки зависит от css, как базовых так и пользовательских, от размера самого числа в метке и других символов (например, метки '0' и '10000$' будут иметь разный размер). Поэтому для качественного размещения нужно знать размеры каждой метки непосредственно в dom после применения всех стилей.

**Comment by lndbaryshnikov** [comment]
Вопрос решен в переписке, принято решение пока оставить как есть. С пунктом в стандартах знаком, здесь же каждая метка рендерится последовательно в dom из следующих соображений: размер метки зависит от css, как базовых так и пользовательских, от размера самого числа в метке и других символов (например, метки '0' и '10000$' будут иметь разный размер). Поэтому для качественного размещения и расчета оптимального количества нужно знать размеры каждой метки непосредственно в dom после применения всех стилей.
