### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/slider-jquery-plugin#12]
![1](https://user-images.githubusercontent.com/19621113/84674654-e9dd2a80-af33-11ea-9a53-214bbcf3f3ca.png)
Именование классов не по БЭМ, поправь пожалуйста везде

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/85158642-33e04c00-b265-11ea-8610-fd29d6c399c6.png)
Миксование у нас запрещено, и плюс непонятно, почему блок `slider` является по сути "пустышкой", просто оборачивающей другой вложенный блок (`jquery-slider`)

**Comment by lndbaryshnikov** [comment]
>> Миксование у нас запрещено

Так-то оно так, только вот как мне по-другому реализовать кастомизацию стилей бегунка..? Сделал по принципу jQuery UI Slider, то есть там `.jquery-slider` - его дефолтный класс, а `.slider` - типа пользовательский, переданный в опциях при инициализации для кастомизации стилей.
Другие более-менее популярные слайдеры предлагают только решения типа `#container .slider { ... }`, где `.slider` - класс слайдера, а а контейнер - пользовательский. Но я думал тот способ что я реализовал более гибкий.

**Comment by lndbaryshnikov** [comment]
> Миксование у нас запрещено
Так-то оно так, только вот как мне по-другому реализовать кастомизацию стилей бегунка..? Сделал по принципу jQuery UI Slider, то есть там `.jquery-slider` - его дефолтный класс, а `.slider` - типа пользовательский, переданный в опциях при инициализации для кастомизации стилей.
Другие более-менее популярные слайдеры предлагают только решения типа `#container .slider { ... }`, где `.slider` - класс слайдера, а а контейнер - пользовательский. Но я думал тот способ что я реализовал более гибкий.

**Comment by lndbaryshnikov** [comment]
> Миксование у нас запрещено

Так-то оно так, только вот как мне по-другому реализовать кастомизацию стилей бегунка..? Сделал по принципу jQuery UI Slider, то есть там `.jquery-slider` - его дефолтный класс, а `.slider` - типа пользовательский, переданный в опциях при инициализации для кастомизации стилей.
Другие более-менее популярные слайдеры предлагают только решения типа `#container .slider { ... }`, где `.slider` - класс слайдера, а а контейнер - пользовательский. Но я думал тот способ что я реализовал более гибкий.

**Comment by lndbaryshnikov** [comment]
> и плюс непонятно, почему блок slider является по сути "пустышкой", просто оборачивающей другой вложенный блок (jquery-slider)

Все что от `jquery-slider` и глубже - это плагин. Блок слайдер это обертка, на которой происходит инициализация плагина. Разве не так принято? Я подумал было что ты имеешь виду что пользовательский контейнер и должен стать начальной точкой бегунка, а не быть пустым контейнером, но в таком случае у пользователя, например, могут быть навешаны стили свои на эту обертку, в таком случае слайдер может быть кривой, так как в приоритете будет пользовательский класс, типа `div class="slider(пользовательский) jquery-slider(плагин)"`.

**Comment by lndbaryshnikov** [comment]
> и плюс непонятно, почему блок slider является по сути "пустышкой", просто оборачивающей другой вложенный блок (jquery-slider)

Все что от `jquery-slider` и глубже - это плагин. Блок слайдер это обертка, на которой происходит инициализация плагина. Разве не так принято..?)

**Comment by lndbaryshnikov** [comment]
> и плюс непонятно, почему блок slider является по сути "пустышкой", просто оборачивающей другой вложенный блок (jquery-slider)

Все что от `jquery-slider` и глубже - это плагин. Блок `.slider` - это обертка, на которой происходит инициализация плагина. Разве не так принято..?)

**Comment by Nelliza** [comment]
> > и плюс непонятно, почему блок slider является по сути "пустышкой", просто оборачивающей другой вложенный блок (jquery-slider)
> 
> Все что от `jquery-slider` и глубже - это плагин. Блок `.slider` - это обертка, на которой происходит инициализация плагина. Разве не так принято..?)

Где принято? ) К примеру, ты часто упоминаешь jQuery UI Slider, вот как там это реализовано:
![1](https://user-images.githubusercontent.com/19621113/85207761-c7804e00-b333-11ea-81f1-ddbd4278ea8e.png)

**Comment by Nelliza** [comment]
> Все что от `jquery-slider` и глубже - это плагин. Блок `.slider` - это обертка, на которой происходит инициализация плагина. Разве не так принято..?)

Где принято? ) К примеру, ты часто упоминаешь jQuery UI Slider, вот как там это реализовано:
![1](https://user-images.githubusercontent.com/19621113/85207761-c7804e00-b333-11ea-81f1-ddbd4278ea8e.png)

**Comment by Nelliza** [comment]
> > Миксование у нас запрещено
> 
> Так-то оно так, только вот как мне по-другому реализовать кастомизацию стилей бегунка..? Сделал по принципу jQuery UI Slider, то есть там `.jquery-slider` - его дефолтный класс, а `.slider` - типа пользовательский, переданный в опциях при инициализации для кастомизации стилей.
> Другие более-менее популярные слайдеры предлагают только решения типа `#container .slider { ... }`, где `.slider` - класс слайдера, а а контейнер - пользовательский. Но я думал тот способ что я реализовал более гибкий.

С миксованием проблему так и не поняла ) Можешь наглядно объяснить, зачем тебе тут миксование?

**Comment by Nelliza** [comment]
https://github.com/lndbaryshnikov/slider-jquery-plugin/blob/9c329f1cc0a76a84e5f7b60c0b525ce8476c02b2/app/src/plugin/View/LabelsView.ts#L68
А почему решил шкалу выделить в отдельный блок? Мне кажется, это неправильно, т.к. шкала не является независимой сущностью, а скорее одним из элементов слайдера

**Comment by Nelliza** [comment]
То же самое относится и к тултипу
