### ISSUE TITLE
Префикс js-

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/slider-jquery-plugin#13]
https://github.com/lndbaryshnikov/slider-jquery-plugin/blob/1672aee53e511fae1d00d544b9cf3de3dc211f2f/app/test-utils/SliderPupPage/SliderPupPage.ts#L105
По нашим стандартам классы, используемые для поиска по DOM, должны начинаться с префикса `js-`. Посмотри плиз еще, где такое встречается

**Comment by lndbaryshnikov** [comment]
> По нашим стандартам классы, используемые для поиска по DOM, должны начинаться с префикса js-. Посмотри плиз еще, где такое встречается

Правило знаю, но вот тут на самом деле немного странно мне кажется. Я понимаю для чего нужно дублирование классов с префиксом. Но для тех случаев когда классы все в html, а тут они все в js, вешаются динамически. Ну то есть класс изначально в js, и привязан к элементу, а не идет поиск элемента в dom по этому классу, тут не может быть никаких ошибок возникнуть если ты захочешь поменять класс и тд. То есть в данном конкретном случае это просто лишние буквы, получается... Да и к тому же это плагин, зачем вводить пользователя в заблуждение этим дублированием классов, что для него может быть непонятным, плюс к тому что это в данном случае и бесполезно...

**Comment by lndbaryshnikov** [comment]
> По нашим стандартам классы, используемые для поиска по DOM, должны начинаться с префикса js-. Посмотри плиз еще, где такое встречается

Правило знаю, но вот конкретно вот этот случай - это для тестов. То есть если даже в тестах происходит поиск по классу плагина, то в плагине все равно должен дублироваться класс с префиксом, да?) А если вынести css классы в отдельное статическое свойство js класса, и брать  их и для функционала плагина, и для тестов из этого свойства? То есть как ни меняй имя класса, никакой код не упадет... А то я еще могу понять когда все классы только в html, а тут все классы в js, вешаются динамически, не хочется дублировать класс просто ради тестового случая.

**Comment by Nelliza** [comment]
Ага, думаю, что если только для тестов, то это лишнее ) Насколько я понимаю, префикс добавляется для того, чтобы максимально дифференцировать смену состояния через JS и стилевые изменения. Но я в нескольких местах встречала отсутствие префикса, скинула ссылку на первое попавшееся, посмотри плиз, встречается ли такое не в тестах

**Comment by lndbaryshnikov** [comment]
> посмотри плиз, встречается ли такое не в тестах

перепроверил, не встречается

**Comment by Nelliza** [comment]
Ок, наверное стоит SliderPupPage.ts перенести в папку с тестами, т.к. она относится непосредственно к ним
