### ISSUE TITLE
Баги слайдера

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/slider-jquery-plugin#2]
При установке max значения = 50 шкала приобретает немного странный вид )
![1](https://user-images.githubusercontent.com/19621113/78601373-587b7900-785d-11ea-9ed6-ccb2b13079a9.png)

**Comment by Nelliza** [comment]
А почему я не могу установить размер шага равным или больше, чем min значение?
![1](https://user-images.githubusercontent.com/19621113/79185682-577bb600-7e20-11ea-9de5-d3d148a59cbf.gif)

**Comment by Nelliza** [comment]
![2](https://user-images.githubusercontent.com/19621113/79185849-bb05e380-7e20-11ea-9ed0-064452ad9cd6.gif)
Значение ползунка не соответствует размеру шага при изменении его значения

**Comment by Nelliza** [comment]
Вообще эти алерты, выскакивающие везде, совсем не комильфо, если честно
![1](https://user-images.githubusercontent.com/19621113/79186264-cf96ab80-7e21-11ea-9bad-6efc3bf9e144.gif)

Например сейчас для того, чтобы поменять max значение, мне нужно сначала уменьшить значение левого ползунка, потом - правого, и только потом опять ввести данные в поле max значения: 3 действия вместо одного, как-то больно получается )

Желательно обойтись без такого, т.к. во фронтенде все-таки важно уделять внимание UI, а такие алерты однозначно являются раздражающими, особенно в этом кейсе, когда это порождает много лишних телодвижений у юзера )

**Comment by Nelliza** [comment]
Шаг не может быть установлен в значение больше max значения

**Comment by Nelliza** [comment]
Также непонятно, почему перемещение одного ползунка приводит в движение второй:
![1](https://user-images.githubusercontent.com/19621113/79698473-cda17200-8291-11ea-854b-0ee9acb19b16.gif)

**Comment by Nelliza** [comment]
А почему размер шага меняется сам по себе при смене max значения? Меняться могут только значения ползунков, подстраиваясь под установленные настройки
![1](https://user-images.githubusercontent.com/19621113/79698542-46083300-8292-11ea-9495-04d357df4461.gif)

**Comment by Nelliza** [comment]
> А почему размер шага меняется сам по себе при смене max значения? Меняться могут только значения ползунков, подстраиваясь под установленные настройки
> ![1](https://user-images.githubusercontent.com/19621113/79698542-46083300-8292-11ea-9495-04d357df4461.gif)

Проблема сохранилась:
![1](https://user-images.githubusercontent.com/19621113/80521289-76875580-8993-11ea-997f-c361be22cfc6.gif)

**Comment by lndbaryshnikov** [comment]
> Проблема сохранилась:
> ![1](https://user-images.githubusercontent.com/19621113/80521289-76875580-8993-11ea-997f-c361be22cfc6.gif)

Убрал автокоррекцию шага, теперь если **min** или **max** неподходящие, то выскакивает тултипчик с ошибкой, также предлагающий ближайшее подходящее значение шага.

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/81743341-27204980-94aa-11ea-9647-85a9b7628189.png)
Шкала не работает при значениях больше 50

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/81743477-6058b980-94aa-11ea-8de7-04cc07600681.png)
Шкала должна иметь числовое отображение, т.к. она не просто декоративный элемент, а несет смысловую нагрузку

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/81743984-423f8900-94ab-11ea-8971-86266f32b76d.png)
Шкала не работает при значениях больше 15

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/82252827-65a97e80-9958-11ea-94e8-606cc30a0bfa.gif)
Вот здесь тоже совсем не очевидное поведение - при установке значения второго ползунка меньше первого почему-то сдвигается первый ползунок.

Тут, как я вижу, может быть 2 варианта - либо не давать второму ползунку присвоить значение меньше первого, либо менять их местами в этом случае (видела такое у нескольких ребят, наверное так даже лучше с точки зрения UI)

**Comment by Nelliza** [comment]
https://github.com/lndbaryshnikov/slider-jquery-plugin/commit/56f50f4526c1c5c3c9b236bc37d65ed3ffda40c8#r39264261

**Comment by lndbaryshnikov** [comment]
941d99cb4d79ace46df48dcf013a2272dbb0cb55

**Comment by lndbaryshnikov** [comment]
> [56f50f4#r39264261](https://github.com/lndbaryshnikov/slider-jquery-plugin/commit/56f50f4526c1c5c3c9b236bc37d65ed3ffda40c8#r39264261)

Исправил 941d99cb4d79ace46df48dcf013a2272dbb0cb55

**Comment by lndbaryshnikov** [comment]
> [56f50f4#r39264261](https://github.com/lndbaryshnikov/slider-jquery-plugin/commit/56f50f4526c1c5c3c9b236bc37d65ed3ffda40c8#r39264261)

Убрал 941d99cb4d79ace46df48dcf013a2272dbb0cb55.

**Comment by Nelliza** [comment]
При наличии двух ползунков установка для них крайних значений с помощью клика по шкале приводит к присваиванию им значений undefined, трекер при этом некорректно смещается:
![3](https://user-images.githubusercontent.com/19621113/85920622-fdff2100-b87d-11ea-8d6f-fd8e0238e0a6.gif)
