### ISSUE TITLE
Линтер

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/slider-jquery-plugin#3]
![1](https://user-images.githubusercontent.com/19621113/79698053-f2e0b100-828e-11ea-906d-9cef607a63f9.png)
Очень много где используется инлайновое отключение правил линтера, это плохая практика. Таким образом ты просто "закрываешь рот" линтеру. Следует убрать закомментированные строки и исправить ошибки, на которые указывает линтер

**Comment by Nelliza** [comment]
От того, что ты перенес отключение части правил в **.eslintrc**, легче как бы не стало ) В этом файле тоже нужно навести порядок и оставить только необходимый минимум, вот такого точно быть не должно:
![1](https://user-images.githubusercontent.com/19621113/80319113-50d54180-8817-11ea-8643-d5d573e51e80.png)

**Comment by lndbaryshnikov** [comment]
* Насчет `no-expcicit-any` - включил обратно, но посмотри пожалуйста на места где выдает предупреждения, там, в части случаев, реально допустим любой аргумент, еще пара случаев - особенность **Conditional Types**, где без `return as any` не добьешься результата, ну, по крайней мере, это единственно решение что я нашел...
* `no-await-in-loop` - оставил пока что выключенным, тоже посмотри пожалуйста, посмотрел что рекомендует линтер, но там `Promise.all` не решение, так как идет работа с состояниями слайдера, в общем я тоже не вижу способов удовлетворить требование airbnb в этом конкретном случае.

**Comment by Nelliza** [comment]
Очень много где используются type assertions - это плохая практика. Тебе стоит изучить, почему их следует избегать, ну и почистить код, конечно )

**Comment by Nelliza** [comment]
Все еще есть много мест, где можно обойтись без type assertions, посмотри плиз еще раз

**Comment by Nelliza** [comment]
Посмотри еще в main.ts плиз )
