### ISSUE TITLE
Модель

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/slider-jquery-plugin#6]
https://github.com/lndbaryshnikov/slider-jquery-plugin/blob/781d36e0e7dfb16d1c7c18bf4f753df7358f15cc/app/src/plugin/Model/SliderModel.ts#L4-L14
Модель не должна ничего знать о css-классах и вообще о привязке к браузеру, она должна быть максимально абстрагирована. Взаимодействие с браузером осуществляется во вьюхах

**Comment by Nelliza** [comment]
Обработку ошибок следует вынести в отдельный модуль

**Comment by lndbaryshnikov** [comment]
> Модель не должна ничего знать о css-классах и вообще о привязке к браузеру, она должна быть максимально абстрагирована. Взаимодействие с браузером осуществляется во вьюхах

Для модели это просто, не знаю, идентификаторы компонентов слайдера, модель не рассматривает это как css классы. Я могу вынести дефолтные классы во вьюху, но кастомные же должны передовать в опциях и проходить через модель. Если это тоже не выход, можешь, пожалуйста, подсказать, или привести пример как стоит организовать.

**Comment by lndbaryshnikov** [comment]
> Обработку ошибок следует вынести в отдельный модуль

Это должен быть сторонний класс, скажем, `ErrorHandler`, с методом типа `validateOptions`? Но тогда классу Валидатора нужно знать опции, их нужно, получается, вынести также в отдельный модуль. Вижу как у тебя сделано. 
Если я понял правильно, то нужно ли как-то организовать эти сторонние классы, типа объединить их всех в "фабрику", или можно просто экспортировать класс Валидатора в Модель и использовать?
Если я понял неправильно, тоже, подскажи, пожалуйста.

**Comment by Nelliza** [comment]
> Для модели это просто, не знаю, идентификаторы компонентов слайдера, модель не рассматривает это как css классы. Я могу вынести дефолтные классы во вьюху, но кастомные же должны передовать в опциях и проходить через модель. Если это тоже не выход, можешь, пожалуйста, подсказать, или привести пример как стоит организовать.

Никакие css-классы не должны проходить через модель, у модели есть публичный метод для получения заданных опций, исходя из которых и производятся нужные действия в рамках зон ответственности слоев приложения

**Comment by Nelliza** [comment]
> > Обработку ошибок следует вынести в отдельный модуль
> 
> Это должен быть сторонний класс, скажем, `ErrorHandler`, с методом типа `validateOptions`? Но тогда классу Валидатора нужно знать опции, их нужно, получается, вынести также в отдельный модуль. Вижу как у тебя сделано.
> Если я понял правильно, то нужно ли как-то организовать эти сторонние классы, типа объединить их всех в "фабрику", или можно просто экспортировать класс Валидатора в Модель и использовать?
> Если я понял неправильно, тоже, подскажи, пожалуйста.

Нет, логика валидации остается в модели

**Comment by Nelliza** [comment]
> Это должен быть сторонний класс, скажем, `ErrorHandler`, с методом типа `validateOptions`? Но тогда классу Валидатора нужно знать опции, их нужно, получается, вынести также в отдельный модуль.

Нет, логика валидации остается в модели
