### ISSUE TITLE
Разделение вьюх

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/slider-jquery-plugin#7]
Согласно заданию, каждый компонент слайдера должен быть представлен отдельным классом, в т.ч. ползунки и трекер - их также следует вынести в отдельные независимые вьюхи

**Comment by lndbaryshnikov** [comment]
Под трекером ты имеешь в виду закрашенную полоску, результат работы опции слайдера `range`? То есть основная вьюха слайдера - это самая основная полоска, бегунки и этот "трекер" - строго отдельные классы?

**Comment by Nelliza** [comment]
Да, все верно

**Comment by Nelliza** [comment]
https://github.com/lndbaryshnikov/slider-jquery-plugin/blob/069cdf342ec9d70a26ba4aca71dbbe0e7b71f659/app/src/plugin/View/MainView.ts#L354-L358
Заметила, что у тебя главная вьюха навешивает обработчики на события нижних, так не должно быть - у каждой из вьюх должна быть своя зона ответственности. У тебя же есть для этой цели готовый обсервер ) Можешь подписать верхнюю вьюху на нижнюю и таким образом слушать нужные события

**Comment by Nelliza** [comment]
https://github.com/lndbaryshnikov/slider-jquery-plugin/blob/07badc0d8ca1194e34f763d71fac3fe74577c4ac/app/src/plugin/View/HandleView.ts#L7
Вот этот тип лишний, и хотя ты его экспортируешь внизу, он нигде не используется
